name: PlugMan
main: me.ryanclancy000.plugman.PlugMan
version: 1.6
description: Plugin Manager Mod for Bukkit
author: ryanclancy000, originally by bekvon.
commands:
  plugman:
    description: Manage Plugins Status.
    usage: /plugman [list]
           /plugman [load|reload|disable|enable|info|usage] [PluginName]
           /plugman [describe] [CommandName] [PluginName]
permissions:
    plugman.admin:
        description: Gives access to all PlugMan commands.
        children:
            plugman.help: true
            plugman.list: true
            plugman.info: true
            plugman.load: true
            plugman.reload: true
            plugman.enable: true
            plugman.disable: true
    plugman.help:
        description: Allows use of the help command.
        default: true
    plugman.list:
        description: Allows use of the list and vlist commands.
        default: true
    plugman.info:
        description: Allows use of the info command.
        default: true
    plugman.load:
        description: Allows use of the load command.
        default: op
    plugman.reload:
        description: Allows use of the reload command.
        default: op
    plugman.enable:
        description: Allows use of the enable command.
        default: op
    plugman.disable:
        description: Allows use of the disable command.
        default: op