name: PlugMan
main: me.ryanclancy000.plugman.PlugMan
version: 2.0
description: Plugin Manager Plugin for Bukkit
author: ryanclancy000
commands:
  plugman:
    description: Manage Plugins Status.
    usage: /plugman [list|help]
           /plugman [load|reload|disable|enable|info] [PluginName]
permissions:
  plugman.admin:
    description: Allows use of all PlugMan commands.
    children:
      plugman.help: true
      plugman.list: true
      plugman.info: true
      plugman.load: true
      plugman.reload: true
      plugman.enable: true
      plugman.disable: true