name: PlugMan
main: me.ryanclancy000.plugman.PlugMan
version: 1.5.1 - Test
description: Plugin Manager Mod for Bukkit
author: ryanclancy000, originally by bekvon.
commands:
  plugman:
    description: Manage Plugins Status.
    usage: /plugman [list]
           /plugman [load|reload|disable|enable|info|usage] [PluginName]
           /plugman [describe] [CommandName] [PluginName]