name: PlugMan
main: me.ryanclancy000.plugman.PlugMan
version: 1.6
description: Plugin Manager Plugin for Bukkit
author: ryanclancy000
commands:
  plugman:
    description: Manage Plugins Status.
    aliases: pm
    usage: /plugman [help|list]
           /plugman [info|load|reload|enable|disable] [PluginName]
permissions:
  plugman.admin:
    description: Allows use of all PlugMan commands.
    children:
      plugman.help: true
      plugman.list: true
      plugman.info: true
      plugman.load: true
      plugman.reload: true
      plugman.enable: true
      plugman.disable: true
  plugman.help:
    description: Allows use of the help command.
    default: true
  plugman.list:
    description: Allows use of the help command.
    default: true
  plugman.info:
    description: Allows use of the help command.
    default: true
  plugman.load:
    description: Allows use of the help command.
    default: op
  plugman.reload:
    description: Allows use of the help command.
    default: op
  plugman.enable:
    description: Allows use of the help command.
    default: op
  plugman.disable:
    description: Allows use of the help command.
    default: op
  